# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fb31bzh9xE5F5E9yUH5-r9no-dq8WEM5
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
import joblib
import warnings

warnings.filterwarnings('ignore')

# Set up the web page
st.set_page_config(page_title="Pharmacogenetic Warfarin Dosing Assistant", layout="wide")
st.title("⚕️ Pharmacogenetic Warfarin Dosing Assistant")
st.markdown("""
**Evidence-based dosing using top predictors from SHAP analysis:**
1. VKORC1 Sensitivity  2. CYP2C9 Activity  3. Ethnicity
4. Genetic Burden  5. Age
*Uses exact same feature encoding as training data*
""")
try:
    model = joblib.load("final_warfarin_model_xgboost.pkl")
except FileNotFoundError:
    st.error("❌ Model file 'final_warfarin_model_xgboost.pkl' not found. Please ensure it is in the app directory.")
    st.stop()

# --- All your original helper functions and mappings are copied below ---
CYP2C9_ACTIVITY = {"Normal": 2.0, "Intermediate": 1.0, "Poor": 0.5}
VKORC1_SENS = {"GG": 0.0, "AG": 1.0, "AA": 2.0}
CYP4F2_SCORE = {"CC": 0.0, "CT": 0.5, "TT": 2.0}

def calculate_genetic_burden(cyp2c9, vkorc1, cyp4f2):
    """Calculate genetic burden as normalized sum of genetic scores (0-2 scale)"""
    cyp2c9_score = CYP2C9_ACTIVITY.get(cyp2c9, 2.0)
    vkorc1_score = VKORC1_SENS.get(vkorc1, 0.0)
    cyp4f2_score = CYP4F2_SCORE.get(cyp4f2, 0.0)
    burden = (
        (2.0 - cyp2c9_score) * 0.4 +
        vkorc1_score * 0.4 +
        cyp4f2_score * 0.2
    )
    return round(burden, 2)

ETHNICITY_OHE = {
    "Asian": {'Ethnicity_Asian': 1, 'Ethnicity_Caucasian': 0, 'Ethnicity_Hispanic': 0, 'Ethnicity_Other': 0},
    "Caucasian": {'Ethnicity_Asian': 0, 'Ethnicity_Caucasian': 1, 'Ethnicity_Hispanic': 0, 'Ethnicity_Other': 0},
    "Hispanic": {'Ethnicity_Asian': 0, 'Ethnicity_Caucasian': 0, 'Ethnicity_Hispanic': 1, 'Ethnicity_Other': 0},
    "Other": {'Ethnicity_Asian': 0, 'Ethnicity_Caucasian': 0, 'Ethnicity_Hispanic': 0, 'Ethnicity_Other': 1},
}

ALCOHOL_OHE = {
    "Heavy": {'Alcohol_Intake_Light': 0, 'Alcohol_Intake_Moderate': 0, 'Alcohol_Intake_Unknown': 0},
    "Light": {'Alcohol_Intake_Light': 1, 'Alcohol_Intake_Moderate': 0, 'Alcohol_Intake_Unknown': 0},
    "Moderate": {'Alcohol_Intake_Light': 0, 'Alcohol_Intake_Moderate': 1, 'Alcohol_Intake_Unknown': 0},
    "Unknown": {'Alcohol_Intake_Light': 0, 'Alcohol_Intake_Moderate': 0, 'Alcohol_Intake_Unknown': 1},
}

SMOKING_OHE = {
    "Former Smoker": {'Smoking_Status_Non-smoker': 1, 'Smoking_Status_Smoker': 0},
    "Non-smoker": {'Smoking_Status_Non-smoker': 1, 'Smoking_Status_Smoker': 0},
    "Smoker": {'Smoking_Status_Non-smoker': 0, 'Smoking_Status_Smoker': 1},
}

DIET_OHE = {
    "High": {'Diet_VitK_Intake_Low': 0, 'Diet_VitK_Intake_Medium': 0},
    "Low": {'Diet_VitK_Intake_Low': 1, 'Diet_VitK_Intake_Medium': 0},
    "Medium": {'Diet_VitK_Intake_Low': 0, 'Diet_VitK_Intake_Medium': 1},
    "Unknown": {'Diet_VitK_Intake_Low': 0, 'Diet_VitK_Intake_Medium': 0},
}

COLUMNS_ORDER = [
    'Age', 'Weight_kg', 'Height_cm', 'CYP2C9_Activity', 'VKORC1_Sensitivity',
    'CYP4F2_Score', 'Genetic_Burden', 'Sex_M',
    'Ethnicity_Asian', 'Ethnicity_Caucasian', 'Ethnicity_Hispanic', 'Ethnicity_Other',
    'Alcohol_Intake_Light', 'Alcohol_Intake_Moderate', 'Alcohol_Intake_Unknown',
    'Smoking_Status_Non-smoker', 'Smoking_Status_Smoker',
    'Diet_VitK_Intake_Low', 'Diet_VitK_Intake_Medium'
]

# --- The main prediction function (unchanged) ---
def predict_warfarin(age, weight, height_cm, cyp2c9, vkorc1, cyp4f2, ethnicity,
                     sex, alcohol, smoking, diet_vitk,
                     amiodarone=False, antibiotics=False, statins=False, aspirin=False):
    """Pharmacogenetic warfarin dose prediction using EXACT training data schema."""
    try:
        # Input processing and feature creation (identical to your Gradio code)
        age = int(age)
        weight = float(weight)
        height_cm = float(height_cm)
        height_m = height_cm / 100.0
        bmi = weight / (height_m ** 2) if height_m > 0 else 0
        genetic_burden = calculate_genetic_burden(cyp2c9, vkorc1, cyp4f2)
        ethnicity_map = ETHNICITY_OHE.get(ethnicity, ETHNICITY_OHE["Caucasian"])

        patient_data = {
            "Age": age, "Weight_kg": weight, "Height_cm": height_cm,
            "CYP2C9_Activity": CYP2C9_ACTIVITY[cyp2c9],
            "VKORC1_Sensitivity": VKORC1_SENS[vkorc1],
            "CYP4F2_Score": CYP4F2_SCORE[cyp4f2],
            "Genetic_Burden": genetic_burden,
            "Sex_M": 1 if sex == "M" else 0,
            **ethnicity_map,
            **ALCOHOL_OHE[alcohol],
            **SMOKING_OHE[smoking],
            **DIET_OHE[diet_vitk],
        }

        for col in COLUMNS_ORDER:
            patient_data.setdefault(col, 0)

        df = pd.DataFrame([patient_data])[COLUMNS_ORDER]
        prediction = float(model.predict(df)[0])

        # --- Generate the structured output ---
        genetic_summary = []
        if cyp2c9 != "Normal":
            effect = "↑ dose req" if cyp2c9 == "Poor" else "↗ dose req"
            genetic_summary.append(f"CYP2C9 {cyp2c9} ({effect})")
        if vkorc1 != "GG":
            effect = "↓ dose req" if vkorc1 == "AA" else "↘ dose req"
            genetic_summary.append(f"VKORC1 {vkorc1} ({effect})")
        if cyp4f2 != "CC":
            effect = "↑ dose req" if cyp4f2 == "TT" else "↗ dose req"
            genetic_summary.append(f"CYP4F2 {cyp4f2} ({effect})")

        # Dose classification
        if prediction < 2.0:
            dose_class, dose_icon, clinical_advice = "VERY LOW", "🔴", "Consider alternative anticoagulants or verify genetic testing"
        elif prediction < 3.0:
            dose_class, dose_icon, clinical_advice = "LOW", "🟡", "Start low, monitor INR closely every 2-3 days initially"
        elif prediction <= 7.0:
            dose_class, dose_icon, clinical_advice = "STANDARD", "🟢", "Standard initiation protocol, check INR after 48-72h"
        elif prediction <= 10.0:
            dose_class, dose_icon, clinical_advice = "HIGH", "🟠", "Higher starting dose, confirm patient factors, monitor INR frequently"
        else:
            dose_class, dose_icon, clinical_advice = "VERY HIGH", "🔴", "Unusual dose - review all inputs, consider drug interactions"

        interactions = []
        if amiodarone: interactions.append("• Amiodarone: Potent CYP2C9 inhibitor - 30-50% dose reduction typical")
        if antibiotics: interactions.append("• Antibiotics: May alter vitamin K synthesis - monitor INR closely")
        if statins: interactions.append("• Statins: Variable interaction - check for specific agent")
        if aspirin: interactions.append("• Aspirin: Increases bleeding risk independent of INR - assess indication")

        # Return a dictionary with all results for the Streamlit interface
        return {
            "prediction": prediction,
            "dose_class": dose_class,
            "dose_icon": dose_icon,
            "clinical_advice": clinical_advice,
            "bmi": bmi,
            "genetic_burden": genetic_burden,
            "genetic_summary": genetic_summary,
            "interactions": interactions,
            "error": None
        }

    except Exception as e:
        return {"error": f"❌ **Error:** {type(e).__name__}: {str(e)}\n\nPlease check all inputs are valid."}

# --- STREAMLIT USER INTERFACE ---
with st.sidebar:
    st.header("📋 Patient Parameters")

    st.subheader("Demographics")
    age = st.slider("Age (years)", 18, 100, 65, help="Older patients generally require lower doses")
    weight = st.number_input("Weight (kg)", 30.0, 250.0, 70.0, step=0.1, help="Higher weight increases dose requirement")
    height_cm = st.number_input("Height (cm)", 120.0, 220.0, 170.0, step=0.1, help="Used for BMI and body surface area calculation")
    sex = st.radio("Sex", ["M", "F"], help="Male patients often require slightly higher doses")
    ethnicity = st.radio("Ethnicity", ["Asian", "Caucasian", "Hispanic", "Other"], index=1, help="Asian ancestry is associated with lower dose requirements")

    st.subheader("Genetics")
    cyp2c9 = st.radio("CYP2C9 Phenotype", ["Normal", "Intermediate", "Poor"], help="Metabolism rate - #2 most important predictor")
    vkorc1 = st.radio("VKORC1 Genotype", ["GG", "AG", "AA"], index=1, help="Sensitivity - #1 most important predictor")
    cyp4f2 = st.radio("CYP4F2 Genotype", ["CC", "CT", "TT"], help="Vitamin K metabolism - minor contributor")

    st.subheader("Lifestyle")
    alcohol = st.selectbox("Alcohol Intake", ["Unknown", "Light", "Moderate", "Heavy"], help="Heavy alcohol use may increase dose requirements")
    smoking = st.selectbox("Smoking Status", ["Non-smoker", "Former Smoker", "Smoker"], help="Smoking induces CYP enzymes - may increase dose")
    diet_vitk = st.selectbox("Dietary Vitamin K", ["Medium", "Low", "High", "Unknown"], help="High vitamin K intake increases dose requirement")

    st.subheader("🚨 Drug Interactions")
    amiodarone = st.checkbox("Amiodarone", help="Potent CYP2C9 inhibitor - reduces dose by 30-50%")
    antibiotics = st.checkbox("Recent Antibiotics", help="May alter gut flora and vitamin K synthesis")
    statins = st.checkbox("Statin Therapy", help="Variable interaction - monitor closely")
    aspirin = st.checkbox("Aspirin Use", help="Increases bleeding risk - assess carefully")

    # The button that triggers the prediction
    calculate_button = st.button("Calculate Warfarin Dose", type="primary", use_container_width=True)

# --- MAIN RESULTS DISPLAY ---
if calculate_button:
    st.header("📄 Clinical Recommendation")
    with st.spinner("Calculating dose based on pharmacogenetic profile..."):
        # Call the prediction function with all inputs
        result = predict_warfarin(
            age, weight, height_cm, cyp2c9, vkorc1, cyp4f2, ethnicity,
            sex, alcohol, smoking, diet_vitk,
            amiodarone, antibiotics, statins, aspirin
        )

    if result["error"]:
        st.error(result["error"])
    else:
        # Display the core recommendation
        st.subheader(f"{result['dose_icon']} Predicted Maintenance Dose: **{result['prediction']:.2f} mg/day**")
        st.caption(f"*Classification: {result['dose_class']} dose range*")

        # Patient Summary Columns
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Age", f"{age}y")
            st.metric("Sex", sex)
        with col2:
            st.metric("Weight", f"{weight} kg")
            st.metric("BMI", f"{result['bmi']:.1f}")
        with col3:
            st.metric("Ethnicity", ethnicity)
            st.metric("Genetic Burden", f"{result['genetic_burden']:.2f}/2.0")

        # Genetic Effects
        if result['genetic_summary']:
            st.write("**Genetic Effects:**")
            for line in result['genetic_summary']:
                st.write(f"- {line}")
        else:
            st.write("**Genetic Effects:** Normal variants")

        # Initial Regimen
        st.success("**Initial Regimen:**")
        st.write(f"Start with **{result['prediction'] * 0.5:.2f} mg** daily for 2 days, then adjust by 0.5–1 mg based on INR response.")
        st.write(f"**Target INR:** 2.0–3.0 (standard) or 2.5–3.5 (mechanical valves)")

        # Drug Interactions
        if result['interactions']:
            st.warning("**Drug Interaction Considerations:**")
            for interaction in result['interactions']:
                st.write(interaction)

        # Clinical Guidance
        st.info(f"**Clinical Guidance:** {result['clinical_advice']}")

        # Disclaimer and Model Info
        with st.expander("**About This Model & Disclaimer**"):
            st.markdown("""
            **Model Performance & Context:**
            - Based on SHAP analysis: VKORC1 > CYP2C9 > Ethnicity > Genetic Burden > Age
            - Model R² = 0.84, RMSE = 0.64 mg (clinically acceptable)
            - Trained on n=30,000 simulated patients
            - Genetic factors explain ~40-50% of dose variability
            - Ethnicity contributes ~15-20% variability

            ⚠️ **For Research/Demonstration Purposes Only**
            This tool is intended for educational and research use. Clinical validation is required before any application in patient care. Always combine algorithmic predictions with clinical judgment and INR monitoring.
            """)
else:
    # Initial state before calculation
    st.info("👈 **Please fill in the patient parameters on the sidebar and click 'Calculate Warfarin Dose'.**")
    # Optional: Display the example cases from your Gradio app
    with st.expander("View Example Patient Scenarios"):
        st.markdown("""
        **1. Standard Case:** 65y Male, 70kg, 170cm, Caucasian, Normal metabolizer (CYP2C9 Normal, VKORC1 GG, CYP4F2 CC), Moderate alcohol, Non-smoker, Medium Vitamin K diet, No interacting drugs.
        **2. High-Risk Case:** 78y Female, 58kg, 155cm, Asian, Poor metabolizer (CYP2C9 Poor, VKORC1 AA, CYP4F2 TT), Unknown alcohol, Non-smoker, Low Vitamin K diet, On Amiodarone and Aspirin.
        **3. Complex Case:** 45y Male, 90kg, 185cm, Hispanic, Intermediate metabolizer (CYP2C9 Intermediate, VKORC1 AG, CYP4F2 CT), Heavy alcohol, Smoker, High Vitamin K diet, On Antibiotics and Statins.
        """)